### PR TITLE
VPN connection additional args

### LINKED ISSUE #43: Feature request - Tunnel details
Thanks for all the hard work.
It seems you can modify the tunnel details in the AWS gui.
Things like phase 1 and phase 2 encryption settings etc.
See https://docs.aws.amazon.com/vpn/latest/s2svpn/VPNTunnels.html

### PR DESCRIPTION
**Pull request by Art3mK**
## Description

Introduce new supported variables for `aws_vpn_connection` resources. Default values are set to `null` so this should be backward compatible with older versions.

## Motivation and Context

Current version doesn't allow set those variables and after AWS replaced my VPN tunnel due to some maintenance - terrafrom apply fails. Also should fix #43 

## Breaking Changes

no breaking changes

## How Has This Been Tested?

No thorough testing, I've updated my own environments with this version

### CODE REVIEW

**Comment by Art3mK** [comment]
ping @miguelaferreira, @antonbabenko

**Review by miguelaferreira — APPROVED** [review]
Thanks for thIS PR @Art3mK! The code looks good to me. I haven't got the infra to test this, but the PR looks simple enough to work.

**Comment by antonbabenko** [comment]
@Art3mK Could you please also add `versions.tf` (copy from [this](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/versions.tf)) in the root and in all examples with the minimum required version of AWS provider to be [3.22](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3220-december-18-2020) ?

**Comment by Art3mK** [comment]
@antonbabenko , I've added `versions.tf`

**Comment by antonbabenko** [comment]
Thanks, @Art3mK !

I have finished this PR in #46, [v2.6.0](https://github.com/terraform-aws-modules/terraform-aws-vpn-gateway/releases/v2.6.0) has been just released.

**Pull request closed without merging**
