### PR TITLE
feat: adding preshared key outputs to module

### PR DESCRIPTION
**Pull request by tomoatki**
## Description
adding preshared keys as outputs

## Motivation and Context
Helping with clean output of module

based on https://github.com/terraform-aws-modules/terraform-aws-vpn-gateway/issues/40

### CODE REVIEW

**Comment by tomoatki** [comment]
Added precommit syntax just to help with the testing happy to remove after it has been merged in under this PR or the other one :)

**Comment by tomoatki** [comment]
@antonbabenko  this okay?

**Comment by antonbabenko** [comment]
Thanks! [v2.10.0](https://github.com/terraform-aws-modules/terraform-aws-vpn-gateway/releases/v2.10.0) has been just released.

**Comment by vkanelov** [comment]
Adding preshared key outputs to module makes my project fails, because preshared  by default is sensitive data. Problem is this output is not deescalated as sensitive and apply fails when preshared  is declarated as sensitive...

**Pull request merged**
