### PR TITLE
Add local and remote IPv4 CIDRs parameters

### PR DESCRIPTION
**Pull request by lgallard**
## Description
https://github.com/binbashar/terraform-aws-vpn-gateway/pull/1

## Motivation and Context
With this PR the IPv4 CIDR on the customer gateway (on-premises) side of the VPN connection and the IPv4 CIDR on the AWS side of the VPN connection can be pass as an input variable

## Breaking Changes
None

## How Has This Been Tested?
Tested on Binbash [Leverage Reference Architecture ](https://github.com/binbashar/le-tf-infra-aws/blob/cb40327bda9d510d4c6297767a8381f8654e92be/network/us-east-1/base-network/vpn_gateways.tf#L15
)

### CODE REVIEW

**Comment by exequielrafaela** [comment]
@lgallard thanks for this PR creation! Looking forward to have this feature available soon :)

**Comment by bryantbiggs** [comment]
Is there a change that is being proposed here? Apologies, I'm a bit confused

**Comment by exequielrafaela** [comment]
@lgallard we probably missed to commit the proposed changes?

**Comment by lgallard** [comment]
@bryantbiggs @exequielrafaela when the PR was created the [local_ipv4_network_cidr](https://github.com/terraform-aws-modules/terraform-aws-vpn-gateway/pull/84/commits/397c6a359537a4162b3607cd44825355c208794b#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbR74) and [remote_ipv4_network_cidr](https://github.com/terraform-aws-modules/terraform-aws-vpn-gateway/pull/84/commits/397c6a359537a4162b3607cd44825355c208794b#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbR75) variables didn't exist (Jan 19), but later they were included in [another PR](https://github.com/terraform-aws-modules/terraform-aws-vpn-gateway/pull/58) (Aug 19).

I made the PR from our master branch instead of the feature branch by mistake and it also got out of date from the base branch, so I'm closing it.

**Pull request closed without merging**
